baseURL: http://knetsolutions.in/
languageCode: en-us
title: knetsolutions - Sofware Defined Networking (SDN) Training and Academic Projects 
theme: hugo-fresh

params:
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/fresh.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: SDN Training and Academic Projects
    # Hero subtitle (optional)
    subtitle: Online Trainings in Software Defined Networking,from beginners to advanced level.  Provide guidance/assistance/consultation in Academic SDN Project. conduct SDN workshop in Colleges.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    # logos to be added for RYU, Mininet, Miniet Wifi, Openflow, OVS, Opendaylight, NetConf, YANG, P4, P4RunTime
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: Trainings
    url: /tr
  - title: Projects
    url: /
  - title: Blog
    sublinks:
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
  - title: Sign up
    url: /
    button: true
  section1:
    title: Top SDN Courses @ 10$
    subtitle: in Udemy
    tiles:
    - title: SDN Crash Course
      icon: mouse-globe
      text: SDN Crash Course (Openflow, Mininet, RYU) Practical/Handson
      url: /
      buttonText: Get started
    - title: NetConf/YANG Course
      icon: laptop-cloud
      text: Learn NetConf ,Yang ,SDN Opendaylight Netconf with practical
      url: /
      buttonText: Get started
    - title: Terraform
      icon: plug-cloud
      text: Learn Terraform with Openstack (practical exercises)
      url: /
      buttonText: Get started
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Bijju, INDIA
      quote: It was an awesome journey with knetsolutions being a pillar support for completion of project and very thankful for assisting during the hardships of my project.
      job: Student
      img: 1
    - name: Haider, Malaysia
      quote: knet solutions is probably the best solution I've ever had in a topic of Software-Defined Networking. Although the content is very difficult for me when I read the books, the lecturer Mr. Suresh Kumar made it easy to understand. The lecturer clearly understands his subject, and made the content well suited for novice to advanced student.
      job: Student
      img: 2
    - name: Udeh, Europe
      quote: Great course handled by an outstanding instructor. What makes it unique is how the theoretical details of every section was explained first before going into the practical application. I strongly recommend it for any one that wants to have a full grasp of SDN.
      job: Professional
      img: 3
    - name: Jose, Dominica
      quote: I loved it, great course. It explained everything I wanted, and needed to learn about RYU. And includes all the coding and documentation about them, so is very complete and easy to understand.
      job: Student
      img: 3    
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
