baseURL: http://knetsolutions.in/
languageCode: en-us
title: knetsolutions - Sofware Defined Networking (SDN) Training and Academic Projects 
theme: hugo-fresh

params:
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/fresh.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Online SDN Training & Academic Projects
    # Hero subtitle (optional)
    subtitle: Online Trainings in Software Defined Networking,from beginners to advanced level.  Provide guidance/assistance/consultation in Academic SDN Project. conduct SDN workshop in Colleges.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    # logos to be added for RYU, Mininet, Miniet Wifi, Openflow, OVS, Opendaylight, NetConf, YANG, P4, P4RunTime
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: Services
    url: /services
  - title: Videos
    url: /
  - title: SDN Projects
    sublinks:
    - title: SDN Project Guidance
      url: /sdn-projects  
    - title: SDN Project Ideas
      url: /sdn-project-ideas
    - title: SDN Mini Projects
      url: /sdn-mini-projects
  - title: SDN Tutorials
    sublinks:
    - title: Testing IPv6 in Mininet
      url: /sdn-tutorials/testing-ipv6-in-mininet
    - title: Mininet Cluster
      url: /sdn-tutorials/mininet-cluster
    - title: Openflow 
      url: /sdn-tutorials/openflow-tutorial
    - title: Mininet 
      url: /sdn-tutorials/mininet-tutorial   
  - title: About Us
    url: /about
  section1:
    title: Our SDN Courses @ 10$
    subtitle: in Udemy
    tiles:
    - title: SDN Crash Course
      icon: mouse-globe
      text: SDN Crash Course (Openflow, Mininet, RYU) Practical/Handson
      url: https://www.udemy.com/course/beginners-sdn-course-with-ryu-controller-practical-handson/?couponCode=TEN_DOLLAR
      buttonText: Get started
    - title: NetConf/YANG Course
      icon: laptop-cloud
      text: Learn NetConf ,Yang ,SDN Opendaylight Netconf with practical
      url: https://www.udemy.com/course/learn-netconf-yang-sdn-opendaylight-with-practical/?couponCode=NETCONF_PROMO
      buttonText: Get started
    - title: Terraform
      icon: plug-cloud
      text: Learn Terraform with Openstack (practical exercises)
      url: https://www.udemy.com/course/learn-terraform-with-openstack-practical-exercises/?couponCode=PROMO1
      buttonText: Get started
  section2:
    title: You're here because you want the best Academic SDN Project guidance and Training.
    subtitle: And we know it
    features:
    - title: Instructor Profile
      text: 17+ years Industry experience in SDN/Networking/Cloud. Telecom/Datacenter SDN Deployment/Development experience, Contributed in RYU, ODL, Opencontrail SDN Controllers and Openstack Cloud Projects. 
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: One to One SDN Project Training in Gotomeeting.
      text: Provides Project training and Support in Gotomeeting(gotomeeting.com) Video meetings. Each session will be recorded(video) and shared to the studends. 
      icon: doc-sync
    - title: Guided 100+ SDN Projects
      text: Guided More than 100+ SDN Projects, studends are from around the world (India, U.S.A, Dominican Rebublic, Brazil, U.K,  Norway, Germany, Malaysia, Vietnam, Saudi Arabia, Yemen, Pakistan) .
      icon: mobile-feed
    - title: Wide SDN Project Topics
      text: MultiDomain SDN Controller, Migrations, DDoS, Flow table Mgmt, Dynamic VLAN/MPLS , Flow Slicing, BGP Attack Detection, Dynamic Load balancing with BGP Speaker, QoS, Server Load balancer, Stateful Firewall, Wireless Handover.
      icon: mobile-feed
  section3: false
    #title: One platform
    #subtitle: To rule them all
    #image: illustrations/mockups/app-mockup.png
    #buttonText: Get started
    #buttonLink: "#"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Bijju, INDIA
      quote: It was an awesome journey with knetsolutions being a pillar support for completion of project and very thankful for assisting during the hardships of my project.Always got immediate response ,when doubts are being asked anytime. 
      job: Student
      img: 1
    - name: Haider, Malaysia
      quote: knet solutions is probably the best solution I've ever had in a topic of Software-Defined Networking. The lecturer clearly understands the subject, and made the content well suited for novice to advanced student.
      job: Student
      img: 2
    - name: Udeh, Europe
      quote: Great course handled by an outstanding instructor. What makes it unique is how the theoretical details of every section was explained first before going into the practical application. I strongly recommend it for any one that wants to have a full grasp of SDN.
      job: Professional
      img: 3  
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/knetsolutions
      # Icons are from Font Awesome
      icon: github
    - link: https://facebook.com/sdntraining
      icon: facebook
    - link: https://www.youtube.com/channel/UCTD6X9_oDqIYs_xpE7moFnQ
      icon: youtube
    bulmalogo: true
    quicklinks:
      column1:
        title: "Contact Us"
        links:
        - text: 129,Saiganesh Nagar,
                Pallikaranai, Chennai,
                India.
        - text: Mobile +919445042007
        - text: Whatsapp +919445042007
        - text: knetsolutions2@gmail.com
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
